sudo: false
language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - tip
  
notifications:
  email: false

install:
  - go get github.com/arnehormann/mirror
  - go get github.com/go-sql-driver/mysql

before_script:
  # for github.com/go-sql-driver/mysql
  - mysql -e 'create database gotest;'
